import React from 'react';

export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    height: '100dvh', // Dynamic viewport height for mobile
    overflow: 'hidden',
    backgroundColor: '#1a1a2e',
    color: '#eee',
    fontFamily: 'system-ui, sans-serif',
  },
  loginBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
    gap: '16px',
  },
  title: {
    margin: 0,
    fontSize: '2rem',
  },
  subtitle: {
    margin: 0,
    color: '#aaa',
  },
  input: {
    padding: '12px 16px',
    fontSize: '1rem',
    borderRadius: '8px',
    border: '1px solid #444',
    backgroundColor: '#2a2a4e',
    color: '#eee',
    width: '280px',
  },
  button: {
    padding: '12px 32px',
    fontSize: '1rem',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: '#4a4ae8',
    color: '#fff',
    cursor: 'pointer',
  },
  error: {
    color: '#ff6b6b',
    margin: 0,
  },
  muted: {
    color: '#888',
    margin: 0,
    fontSize: '0.9rem',
    position: 'relative',
  },
  statsIcon: {
    marginLeft: '8px',
    cursor: 'help',
    color: '#6b6bff',
    fontSize: '1rem',
    fontWeight: 'bold',
  },
  statsTooltip: {
    position: 'fixed',
    top: '100px',
    left: '20px',
    backgroundColor: '#2a2a4e',
    border: '1px solid #4a4ae8',
    borderRadius: '8px',
    padding: '12px',
    zIndex: 1001,
    minWidth: '320px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.3)',
  },
  statsSection: {
    marginBottom: '8px',
  },
  statsSectionTitle: {
    fontWeight: 'bold',
    color: '#6b6bff',
    marginBottom: '6px',
    fontSize: '0.85rem',
  },
  statsRow: {
    fontSize: '0.8rem',
    marginBottom: '4px',
    color: '#ddd',
  },
  statsSeparator: {
    height: '1px',
    backgroundColor: '#444',
    margin: '10px 0',
  },
  mainLayout: {
    display: 'flex',
    height: '100dvh', // Dynamic viewport height for mobile (falls back to 100vh)
    overflow: 'hidden',
  },
  sidebar: {
    width: '280px',
    backgroundColor: '#16162a',
    display: 'flex',
    flexDirection: 'column',
    borderRight: '1px solid #333',
    overflow: 'hidden',
    transition: 'width 0.2s ease',
  },
  sidebarCollapsed: {
    width: '0px',
    minWidth: 0,
    overflow: 'hidden',
    borderRight: 'none',
    padding: 0,
  },
  collapsedSidebarStrip: {
    width: '40px',
    minWidth: '40px',
    backgroundColor: '#16162a',
    borderRight: '1px solid #333',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    paddingTop: '16px',
  },
  expandSidebarButton: {
    background: 'none',
    border: 'none',
    fontSize: '1.2rem',
    color: '#888',
    cursor: 'pointer',
    padding: '4px 8px',
  },
  collapseSidebarButton: {
    background: 'none',
    border: 'none',
    fontSize: '1.2rem',
    color: '#888',
    cursor: 'pointer',
    marginLeft: '4px',
    padding: '2px 6px',
  },
  sidebarMobile: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    height: '100vh',
    zIndex: 1000,
    transition: 'transform 0.3s ease',
  },
  sidebarHidden: {
    transform: 'translateX(-100%)',
  },
  sidebarOverlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 999,
  },
  hamburgerButton: {
    position: 'fixed' as const,
    top: '12px',
    left: '12px',
    zIndex: 998,
    backgroundColor: '#2a2a4e',
    border: 'none',
    borderRadius: '8px',
    padding: '8px 12px',
    fontSize: '1.5rem',
    color: '#eee',
    cursor: 'pointer',
  },
  closeSidebarButton: {
    background: 'none',
    border: 'none',
    fontSize: '1.2rem',
    color: '#888',
    cursor: 'pointer',
    marginLeft: '8px',
  },
  sidebarHeader: {
    padding: '20px',
    borderBottom: '1px solid #333',
  },
  sidebarHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sidebarTitle: {
    margin: 0,
    fontSize: '1.2rem',
  },
  exitProjectButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#888',
    marginLeft: 'auto',
    fontSize: '0.9rem',
  },
  logoutButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '1.2rem',
    color: '#888',
  },
  editInput: {
    flex: 1,
    padding: '4px 8px',
    fontSize: '0.95rem',
    borderRadius: '4px',
    border: '1px solid #4a4ae8',
    backgroundColor: '#2a2a4e',
    color: '#eee',
    marginRight: '8px',
    minWidth: 0,
    overflow: 'visible',
  },
  statsBox: {
    padding: '16px',
    borderTop: '1px solid #333',
  },
  statsText: {
    margin: '4px 0',
    fontSize: '0.85rem',
    color: '#aaa',
  },
  chatArea: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0, // Important for flex children to allow shrinking
    maxHeight: '100%',
    overflow: 'hidden',
  },
  chatHeader: {
    padding: '16px 20px',
    borderBottom: '1px solid #333',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flexShrink: 0,
    overflowX: 'auto',
  },
  chatHeaderMobile: {
    paddingLeft: '56px', // Clear the fixed hamburger button
    WebkitOverflowScrolling: 'touch',
  },
  chatTitle: {
    margin: 0,
    fontSize: '1.1rem',
    flex: 1,
    minWidth: '80px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  viewerCount: {
    fontSize: '0.8rem',
    color: '#8f8fa0',
    background: '#2a2a4e',
    padding: '4px 10px',
    borderRadius: '12px',
    whiteSpace: 'nowrap' as const,
  },
  modelSelector: {
    background: '#2a2a4e',
    color: '#fff',
    border: '1px solid #4a4a6e',
    borderRadius: '6px',
    padding: '6px 10px',
    fontSize: '0.9rem',
    cursor: 'pointer',
    marginRight: '8px',
    flexShrink: 0,
  },
  reloadButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '1.2rem',
    padding: '4px 8px',
    borderRadius: '4px',
    transition: 'background-color 0.2s',
  } as React.CSSProperties & { ':hover'?: React.CSSProperties },
  messagesContainer: {
    flex: 1,
    overflowY: 'auto',
    padding: '20px',
    minHeight: 0, // Important for flex children to allow shrinking
  },
  message: {
    padding: '16px',
    borderRadius: '8px',
    marginBottom: '12px',
  },
  messageRole: {
    fontWeight: 'bold',
    marginBottom: '8px',
    fontSize: '0.85rem',
    color: '#aaa',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  editMessageButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.9rem',
    padding: '2px 6px',
    borderRadius: '4px',
    opacity: 1,  // Fully visible always
    transition: 'background-color 0.2s',
  },
  editMessageTextarea: {
    width: '100%',
    minHeight: '100px',
    padding: '12px',
    fontSize: '1rem',
    borderRadius: '8px',
    border: '1px solid #555',
    backgroundColor: '#1a1a2e',
    color: '#eee',
    resize: 'vertical',
    fontFamily: 'inherit',
    lineHeight: 1.5,
    marginBottom: '8px',
  } as React.CSSProperties,
  editMessageActions: {
    display: 'flex',
    gap: '8px',
    justifyContent: 'flex-end',
  },
  messageContent: {
    lineHeight: 1.5,
  },
  messageTokens: {
    fontSize: '0.75rem',
    color: '#666',
  },
  messageFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '8px',
  },
  messageTimestamp: {
    fontSize: '0.75rem',
    color: '#666',
    marginLeft: 'auto',
  },
  branchNav: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '0.75rem',
    color: '#888',
  },
  branchNavButton: {
    background: 'none',
    border: 'none',
    color: '#888',
    cursor: 'pointer',
    padding: '2px 4px',
    fontSize: '0.7rem',
    borderRadius: '3px',
    transition: 'background-color 0.2s, color 0.2s',
  },
  branchNavText: {
    minWidth: '30px',
    textAlign: 'center' as const,
  },
  reasoningContainer: {
    backgroundColor: '#252540',
    borderRadius: '6px',
    marginBottom: '12px',
    cursor: 'pointer',
    border: '1px solid #3a3a5e',
  },
  reasoningHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    fontSize: '0.85rem',
    color: '#888',
  },
  reasoningLabel: {
    fontStyle: 'italic',
  },
  reasoningContent: {
    padding: '0 12px 12px 12px',
    fontSize: '0.9rem',
    color: '#aaa',
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap' as const,
    borderTop: '1px solid #3a3a5e',
    paddingTop: '12px',
  },
  inputArea: {
    padding: '16px',
    borderTop: '1px solid #333',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
    flexShrink: 0, // Prevent input area from shrinking
    backgroundColor: '#1a1a2e', // Ensure background is visible
  },
  messageInput: {
    width: '100%',
    padding: '12px 30px 12px 12px',
    fontSize: '1rem',
    borderRadius: '8px',
    border: '1px solid #444',
    backgroundColor: '#2a2a4e',
    color: '#eee',
    resize: 'none',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
    lineHeight: '1.5',
  },
  sendButton: {
    padding: '12px 24px',
    fontSize: '1rem',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: '#4a4ae8',
    color: '#fff',
    cursor: 'pointer',
    alignSelf: 'flex-end',
  },
  buttonColumn: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
    alignSelf: 'flex-end',
  },
  updateButton: {
    padding: '8px 16px',
    fontSize: '0.85rem',
    borderRadius: '8px',
    border: '1px solid #444',
    color: '#ccc',
    cursor: 'pointer',
  },
  modalOverlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2000,
  },
  modal: {
    backgroundColor: '#1e1e3a',
    borderRadius: '12px',
    padding: '24px',
    width: '90%',
    maxWidth: '600px',
    maxHeight: '80vh',
    display: 'flex',
    flexDirection: 'column' as const,
    border: '1px solid #4a4ae8',
  },
  modalTitle: {
    margin: '0 0 8px 0',
    fontSize: '1.3rem',
    color: '#eee',
  },
  modalDescription: {
    margin: '0 0 16px 0',
    fontSize: '0.9rem',
    color: '#888',
  },
  updatesTextarea: {
    width: '100%',
    minHeight: '200px',
    padding: '12px',
    fontSize: '1rem',
    borderRadius: '8px',
    border: '1px solid #444',
    backgroundColor: '#2a2a4e',
    color: '#eee',
    resize: 'vertical',
    fontFamily: 'inherit',
    lineHeight: 1.5,
    marginBottom: '16px',
    boxSizing: 'border-box',
  } as React.CSSProperties,
  modalFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tokenCount: {
    fontSize: '0.85rem',
  },
  modalActions: {
    display: 'flex',
    gap: '12px',
    justifyContent: 'flex-end',
  },
  modalCancelButton: {
    padding: '10px 20px',
    fontSize: '1rem',
    borderRadius: '8px',
    border: '1px solid #444',
    backgroundColor: 'transparent',
    color: '#ccc',
    cursor: 'pointer',
  },
  modalSaveButton: {
    padding: '10px 20px',
    fontSize: '1rem',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: '#4a4ae8',
    color: '#fff',
    cursor: 'pointer',
  },
  resizeHandle: {
    position: 'absolute',
    top: '0px',
    right: '0px',
    width: '24px',
    height: '24px',
    cursor: 'ns-resize',
    color: '#666',
    fontSize: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    userSelect: 'none',
    zIndex: 10,
    fontWeight: 'bold',
    letterSpacing: '-2px',
    backgroundColor: '#2a2a4e',
    borderTopRightRadius: '8px',
  },
  noChat: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#666',
  },
  errorBanner: {
    position: 'fixed',
    bottom: '20px',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: '#ff6b6b',
    color: '#fff',
    padding: '12px 20px',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  docsRefreshedBanner: {
    position: 'fixed',
    bottom: '60px',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: '#4caf50',
    color: '#fff',
    padding: '12px 20px',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  errorClose: {
    background: 'none',
    border: 'none',
    color: '#fff',
    fontSize: '1.2rem',
    cursor: 'pointer',
  },
  chatName: {
    flex: 1,
    cursor: 'pointer',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  chatActions: {
    display: 'flex',
    gap: '4px',
  },
  iconButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px',
    fontSize: '0.9rem',
    opacity: 0.6,
  },
  iconButtonCheck: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px',
    fontSize: '0.9rem',
    color: '#4ade80',
  },
  iconButtonX: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px',
    fontSize: '0.9rem',
    color: 'hsl(0, 98%, 75%)',
  },
  section: {
    borderBottom: '1px solid #333',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 16px',
    cursor: 'pointer',
    fontWeight: 'bold',
    fontSize: '0.9rem',
    color: '#aaa',
  },
  sectionHeaderClickable: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
  },
  addButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '1.2rem',
    color: '#4a4ae8',
    marginLeft: 'auto',
    padding: '0 4px',
  },
  expandIcon: {
    fontSize: '0.7rem',
  },
  sectionList: {
    padding: '0 8px 8px 8px',
  },
  listItem: {
    padding: '10px 12px',
    borderRadius: '6px',
    cursor: 'pointer',
    marginBottom: '2px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  mutedSmall: {
    color: '#666',
    fontSize: '0.85rem',
    margin: '8px 12px',
  },
  seeMoreLink: {
    padding: '8px 12px',
    color: '#4a4ae8',
    fontSize: '0.9rem',
    cursor: 'pointer',
    textAlign: 'center' as const,
    marginTop: '4px',
  },
  listViewHeader: {
    padding: '20px',
    borderBottom: '1px solid #333',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
  },
  listViewTitle: {
    margin: 0,
    fontSize: '1.5rem',
    flex: 1,
    textAlign: 'center' as const,
  },
  backButton: {
    padding: '8px 16px',
    fontSize: '1rem',
    borderRadius: '6px',
    border: 'none',
    backgroundColor: '#2a2a4e',
    color: '#eee',
    cursor: 'pointer',
  },
  listViewAddButton: {
    padding: '8px 16px',
    fontSize: '1rem',
    borderRadius: '6px',
    border: 'none',
    backgroundColor: '#4a4ae8',
    color: '#fff',
    cursor: 'pointer',
  },
  listViewContent: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '20px',
  },
  listViewItem: {
    padding: '16px 20px',
    borderRadius: '8px',
    marginBottom: '8px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    border: '1px solid #333',
  },
  listViewItemName: {
    flex: 1,
    fontSize: '1.1rem',
    cursor: 'pointer',
  },
  listViewEmpty: {
    textAlign: 'center' as const,
    marginTop: '60px',
    color: '#666',
  },
  loadingMore: {
    textAlign: 'center' as const,
    padding: '12px',
    color: '#888',
    fontSize: '0.9rem',
    fontStyle: 'italic',
  },
  loadingMoreMessages: {
    textAlign: 'center' as const,
    padding: '12px',
    color: '#888',
    fontSize: '0.9rem',
    fontStyle: 'italic',
    backgroundColor: '#1a1a2e',
  },

  // Project Landing Page Styles
  projectLanding: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100%',
    overflow: 'hidden',
  },
  projectLandingHeader: {
    padding: '20px',
    borderBottom: '1px solid #333',
    flexShrink: 0,
  },
  projectLandingTitle: {
    margin: 0,
    fontSize: '1.5rem',
    color: '#eee',
  },
  projectLandingContent: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
    gap: '1px',
    backgroundColor: '#333',
  },
  projectChatsColumn: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    backgroundColor: '#1a1a2e',
    overflow: 'hidden',
    minWidth: 0,
  },
  projectConfigColumn: {
    width: '380px',
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    backgroundColor: '#1a1a2e',
    overflow: 'auto',
  },
  projectSection: {
    padding: '16px',
    borderBottom: '1px solid #333',
  },
  projectSectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  projectSectionTitle: {
    margin: 0,
    fontSize: '1rem',
    color: '#aaa',
    fontWeight: 600,
  },
  projectAddButton: {
    padding: '6px 12px',
    fontSize: '0.85rem',
    borderRadius: '6px',
    border: 'none',
    backgroundColor: '#4a4ae8',
    color: '#fff',
    cursor: 'pointer',
  },
  chatSearchInput: {
    margin: '0 16px 12px 16px',
    padding: '10px 12px',
    fontSize: '0.95rem',
    borderRadius: '8px',
    border: '1px solid #444',
    backgroundColor: '#2a2a4e',
    color: '#eee',
    outline: 'none',
  },
  projectChatsList: {
    flex: 1,
    overflow: 'auto',
    padding: '0 16px 16px 16px',
  },
  chatGroupHeader: {
    fontSize: '0.8rem',
    fontWeight: 600,
    color: '#666',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
    marginTop: '16px',
    marginBottom: '8px',
  },
  chatCard: {
    padding: '12px 14px',
    marginBottom: '8px',
    borderRadius: '8px',
    backgroundColor: '#252542',
    border: '1px solid #333',
    cursor: 'pointer',
    transition: 'background-color 0.15s',
  },
  chatCardName: {
    fontSize: '1rem',
    fontWeight: 500,
    color: '#eee',
    marginBottom: '4px',
  },
  chatCardPreview: {
    fontSize: '0.85rem',
    color: '#888',
    marginBottom: '8px',
    lineHeight: 1.4,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  chatCardMeta: {
    display: 'flex',
    gap: '12px',
    fontSize: '0.75rem',
    color: '#666',
  },
  tokenBadge: {
    fontSize: '0.8rem',
    color: '#888',
    backgroundColor: '#2a2a4e',
    padding: '2px 8px',
    borderRadius: '4px',
  },
  instructionsPreview: {
    fontSize: '0.9rem',
    color: '#aaa',
    lineHeight: 1.5,
    marginBottom: '12px',
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
  },
  editInstructionsButton: {
    padding: '8px 16px',
    fontSize: '0.9rem',
    borderRadius: '6px',
    border: '1px solid #4a4ae8',
    backgroundColor: 'transparent',
    color: '#4a4ae8',
    cursor: 'pointer',
    width: '100%',
  },
  projectModelSelector: {
    padding: '8px 12px',
    backgroundColor: '#2a2a4e',
    border: '1px solid #3a3a5e',
    borderRadius: '4px',
    color: '#e0e0e0',
    fontSize: '14px',
    width: '100%',
    marginBottom: '8px',
    cursor: 'pointer',
  },
  projectModelHelperText: {
    fontSize: '0.8rem',
    color: '#888',
    margin: 0,
  },
  filesList: {
    marginBottom: '12px',
  },
  fileItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '8px 0',
    borderBottom: '1px solid #333',
    gap: '8px',
  },
  fileName: {
    flex: 1,
    fontSize: '0.9rem',
    color: '#ccc',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  filenameTooltip: {
    position: 'fixed' as const,
    backgroundColor: '#2a2a4e',
    border: '1px solid #4a4ae8',
    borderRadius: '6px',
    padding: '6px 10px',
    zIndex: 1001,
    fontSize: '0.85rem',
    color: '#eee',
    boxShadow: '0 4px 12px rgba(0,0,0,0.3)',
    maxWidth: '400px',
    wordBreak: 'break-all' as const,
  },
  fileTokens: {
    fontSize: '0.8rem',
    color: '#888',
    flexShrink: 0,
  },
  fileDeleteButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px',
    fontSize: '0.85rem',
    opacity: 0.6,
    flexShrink: 0,
  },
  fileCheckbox: {
    width: '16px',
    height: '16px',
    cursor: 'pointer',
    flexShrink: 0,
    accentColor: '#4a4ae8',
  },
  uploadButton: {
    padding: '8px 16px',
    fontSize: '0.9rem',
    borderRadius: '6px',
    border: '1px solid #444',
    backgroundColor: '#2a2a4e',
    color: '#ccc',
    cursor: 'pointer',
    width: '100%',
  },

  // Agent badge styles (pipeline file routing)
  agentBadges: {
    display: 'inline-flex' as const,
    gap: '3px',
    marginLeft: '4px',
    flexShrink: 0,
  },
  agentBadgeActive: {
    display: 'inline-flex' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    width: '20px',
    height: '18px',
    fontSize: '0.7rem',
    fontWeight: 700,
    borderRadius: '3px',
    cursor: 'pointer',
    backgroundColor: '#6b5ce7',
    color: '#fff',
    userSelect: 'none' as const,
  },
  agentBadgeInactive: {
    display: 'inline-flex' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    width: '20px',
    height: '18px',
    fontSize: '0.7rem',
    fontWeight: 700,
    borderRadius: '3px',
    cursor: 'pointer',
    backgroundColor: 'transparent',
    color: '#666',
    border: '1px solid #444',
    userSelect: 'none' as const,
  },
  agentTabBar: {
    display: 'flex' as const,
    gap: '2px',
    marginBottom: '12px',
    borderBottom: '1px solid #333',
    paddingBottom: '0',
  },
  agentTab: {
    padding: '8px 16px',
    fontSize: '0.9rem',
    background: 'none',
    border: 'none',
    borderBottom: '2px solid transparent',
    color: '#888',
    cursor: 'pointer',
    display: 'flex' as const,
    alignItems: 'center' as const,
    gap: '6px',
  },
  agentTabActive: {
    color: '#e0e0e0',
    borderBottomColor: '#6b5ce7',
  },
  agentTabTokens: {
    fontSize: '0.75rem',
    color: '#666',
  },

  // Chat file attachment styles
  inputRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'flex-end',
    width: '100%',
  },
  attachButtonContainer: {
    position: 'relative' as const,
    flexShrink: 0,
  },
  attachButton: {
    width: '40px',
    height: '40px',
    borderRadius: '8px',
    border: '1px solid #444',
    backgroundColor: '#2a2a4e',
    color: '#ccc',
    fontSize: '1.5rem',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  attachMenu: {
    position: 'absolute' as const,
    bottom: '48px',
    left: 0,
    backgroundColor: '#2a2a4e',
    border: '1px solid #444',
    borderRadius: '8px',
    padding: '4px',
    minWidth: '140px',
    zIndex: 100,
    boxShadow: '0 4px 12px rgba(0,0,0,0.3)',
  },
  attachMenuItem: {
    display: 'block',
    width: '100%',
    padding: '10px 12px',
    border: 'none',
    backgroundColor: 'transparent',
    color: '#ccc',
    fontSize: '0.9rem',
    textAlign: 'left' as const,
    cursor: 'pointer',
    borderRadius: '6px',
  },
  stagedFilesBar: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '8px',
    padding: '8px',
    backgroundColor: '#252542',
    borderRadius: '8px',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  stagedFileChip: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px 8px',
    backgroundColor: '#3a3a5e',
    borderRadius: '6px',
    fontSize: '0.85rem',
  },
  stagedFileName: {
    color: '#ccc',
  },
  stagedFileRemove: {
    background: 'none',
    border: 'none',
    color: '#888',
    cursor: 'pointer',
    padding: '2px',
    fontSize: '0.8rem',
    lineHeight: 1,
  },
  attachedFilesDisplay: {
    marginBottom: '8px',
    padding: '6px 10px',
    backgroundColor: 'rgba(74, 74, 232, 0.15)',
    borderRadius: '6px',
    fontSize: '0.85rem',
  },
  attachedFilesSingle: {
    color: '#aaa',
  },
  attachedFilesDetails: {
    cursor: 'pointer',
  },
  attachedFilesSummary: {
    color: '#aaa',
    outline: 'none',
  },
  attachedFilesExpanded: {
    marginTop: '6px',
    paddingLeft: '8px',
  },
  attachedFileItem: {
    color: '#888',
    fontSize: '0.8rem',
    padding: '2px 0',
  },
  editModeAttachedFiles: {
    marginBottom: '8px',
    padding: '8px 10px',
    backgroundColor: 'rgba(74, 74, 232, 0.1)',
    borderRadius: '6px',
    fontSize: '0.85rem',
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '8px',
    alignItems: 'center',
  },
  editModeFilesLabel: {
    color: '#888',
    marginRight: '4px',
  },
  editModeFileName: {
    color: '#aaa',
    backgroundColor: 'rgba(74, 74, 232, 0.2)',
    padding: '2px 8px',
    borderRadius: '4px',
  },

  // State change notification cards
  stateNotificationsContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
    padding: '8px 60px 4px 60px',
  },
  stateNotificationsContainerMobile: {
    padding: '8px 12px 4px 12px',
  },
  rsNotification: {
    padding: '4px 10px',
    borderRadius: '4px',
    fontSize: '12px',
    fontFamily: 'monospace',
    background: 'rgba(255,255,255,0.03)',
    color: '#ccc',
    borderLeft: '3px solid #4caf50',
  },
  rsNotificationNegative: {
    borderLeft: '3px solid #f44336',
  },
  memoryNotification: {
    padding: '4px 10px',
    borderRadius: '4px',
    fontSize: '12px',
    fontFamily: 'monospace',
    background: 'rgba(255,255,255,0.03)',
    color: '#ccc',
    borderLeft: '3px solid #9c27b0',
  },
  notificationLabel: {
    fontWeight: 600,
    marginRight: '4px',
  },
  notificationReason: {
    color: '#999',
    fontStyle: 'italic' as const,
  },
  notificationQuote: {
    color: '#888',
    fontSize: '11px',
    marginTop: '2px',
  },
};
